# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64e5f952bacc03785ea08e804a71798d9a132da18d8202df4220a1ac8b64ed4ded4fb0159a23abff88c501f5f798ff6ac51fbedcf0ae511da95f9d3226dffb0e

test:
  secret_key_base: 6a27c04e7eef218e91c93afaa1e184504420e3a25c967883f76a935c985eb99ca888f766aaaa4691fab813143d4301f123a1c16f369e4e9fd6fb5c2ec87eb019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
